### ISSUE TITLE
Create Stable Release

### ISSUE THREAD

**Issue by thomaswelton** [emberlabs/gravatarlib#6]
@damianb Hey, there is no stable release for this package. Would you be able to make one?
You can create a new tag/release from the github site and this way we'd be able to consume this package with composer minimum stability `stable`

Thanks

**Comment by katanacrimson** [comment]
I resigned from development of these projects and no longer have commit access nor the desire to continue handling them.

**Comment by thomaswelton** [comment]
@damianb hoping you can still help. Do you know who has push access and who I'd be able to speak to if I want to maintain this repo instead of creating my own fork?

**Comment by thomaswelton** [comment]
Created https://github.com/thomaswelton/gravatarlib

**Comment by katanacrimson** [comment]
give @samt a shout.
